import type { Metadata } from "next";
import localFont from "@next/font/local"
import "./globals.css";

const giselle = localFont({
  src: [
    {
      path: '../../public/fonts/FHGiselle-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/FHGiselle-Regular.woff2',
      weight: '700',
      style: 'medium',
    }
  ],
  variable: '--font-giselle'
})

export const metadata: Metadata = {
  title: "ASRI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${giselle.variable} font-sans`}>{children}</body>
    </html>
  );
}