export const geoplatform = [
	{
		id: 1,
		unor: 'SDA', 
		sektor: ['Irigasi', 'Something'],
		nama: 'Prioritas Irigasi',
        loc: 'all',
		link: 'https://ee-ismailfaruqi.projects.earthengine.app/view/indonesia-surface-irrigation-assessment-tool',
		image: 'ee_sda.png',
		isArchive: false,
		isDelete: false,
	},
	{
		id: 2,
		unor: 'Cipta Karya', 
		sektor: ['TPA'],
		nama: 'Spatial Prioritization For Indonesia Wildfire Mitigation',
        loc: 'all',
		link: 'https://cokrosantoso.users.earthengine.app/view/wildfireindonesia',
		image: 'ee_ck.png',
		isArchive: false,
		isDelete: false,
	},
	{
		id: 3,
		unor: 'Bina Marga', 
		sektor: ['Jalan Tol'],
		nama: 'Road Network Index of Southeast Asia Animal Habitats',
        loc: 'all',
		link: 'https://cokrosantoso.users.earthengine.app/view/roadconflict',
		image: 'ee_bm.png',
		isArchive: false,
		isDelete: false,
	},
	{
		id: 4,
		unor: 'Perumahan', 
		sektor: ['Rumah Susun'],
		nama: 'Spatial Distribution of Aerosol Optical Depth (AOD) as a New Instrument in Minimizing Coronavirus Fatality Rate',
        loc: 'all',
		link: 'https://ismailfaruqi.users.earthengine.app/view/aod-as-a-new-instrument',
		image: 'ee_house.png',
		isArchive: false,
		isDelete: false,
	},
	{
		id: 5,
		unor: 'Perumahan', 
		sektor: ['Rumah Susun'],
		nama: 'Spatial Distribution of Aerosol Optical Depth (AOD) as a New Instrument in Minimizing Coronavirus Fatality Rate',
        loc: 'all',
		link: 'https://ismailfaruqi.users.earthengine.app/view/aod-as-a-new-instrument',
		image: 'ee_house.png',
		isArchive: false,
		isDelete: false,
	},
	{
		id: 6,
		unor: 'Perumahan', 
		sektor: ['Rumah Susun'],
		nama: 'Spatial Distribution of Aerosol Optical Depth (AOD) as a New Instrument in Minimizing Coronavirus Fatality Rate',
        loc: 'all',
		link: 'https://ismailfaruqi.users.earthengine.app/view/aod-as-a-new-instrument',
		image: 'ee_house.png',
		isArchive: false,
		isDelete: false,
	},
];